@startuml

Header Git Workflow: Main-Development-QA-Production

group Adding a feature

  feature <-- main: Cut feature branch
  feature ->o main: After approval, merge feature
  hnote over main: Git tag vX.X.X
   
end

group Promoting a feature

  main->o development: Merge main into development
  development ->o qa: Merge development into qa
  qa ->o production: Merge qa into production

end

@enduml

