@startuml

Header Git Workflow: PRs Target Master, Merge to Deployment Branches

group Adding a feature

  feature <-- master: Cut feature branch
  feature ->o master: After approval, merge feature
  hnote over master: Git tag vX.X.X
   
end

group Promoting a feature

  master ->o development: Optionally merge to development for testing
  master ->o qa: Merge master into qa
  master ->o production: Merge master into production

end

@enduml

